#!/usr/bin/env bash

source ./utils/colors.sh

all()
{
    shw_start "Backing up"
}

if [ "$(uname)" == "Darwin" ]; then
    shw_info  "OSX System Detected\n"
    all
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    shw_info "Linux System Detected\n"
    all
fi

shw_success "Backing up"