#!/usr/bin/env bash
INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ./utils/colors.sh

all()
{
    shw_start "Installing"
    ./add_symlinks
}

if [ "$(uname)" == "Darwin" ]; then
    shw_info  "OSX System Detected"
    all
    ./install_scripts/osx.sh
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    shw_info "Linux System Detected"
    all
fi


shw_success "Installing"
