#!/bin/bash
PERM_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${PERM_DIR}/utils/utils.sh
source ./utils/utils.sh 2> /dev/null

#Setup up proper permissions
shw_info "All files with .sh to -exec"
find . -name "*.sh" -exec chmod +x {} \;
