#!/usr/bin/env bash
CRON_SETUP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ./utils/utils.sh

main() {
    shw_start_init "Installing cron tasks on ubuntu or osx"
    if [ "$(uname)" == "Darwin" ]; then
        shw_info "OSX System Detected"
        clr_blue "\nCurrent Crontab:"
        sudo crontab -l
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        shw_info "Linux System Detected"
        shw_info "cp ${CRON_SETUP_DIR}/configs/ubuntu.root.crontab /var/spool/cron/crontabs/root"
        sudo cp "${CRON_SETUP_DIR}/configs/ubuntu.root.crontab" "/var/spool/cron/crontabs/root"
        sudo chown root:root /var/spool/cron/crontabs/root
        sudo chmod 600 /var/spool/cron/crontabs/root
        clr_blue "\nCurrent /var/spool/cron/crontabs/:"
        sudo ls -lah /var/spool/cron/crontabs/
        clr_blue "\nCurrent Crontab:"
        sudo crontab -l
        clr_blue "\n"
    fi

    shw_success_final "Installing cron tasks on ubuntu or osx"
}
main
