#!/usr/bin/env bash
INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ./utils/utils.sh

update_z() {
  #update z
  local filename=z.sh
  wget https://raw.githubusercontent.com/rupa/z/master/$filename -nv
  mv $filename ${INSTALL_DIR}/configs/
  shw_success "Updated Z.sh"
}

update_terminals() {
  #Update pretzo
  cd "${ZDOTDIR:-$HOME}/.zprezto" && git pull && git submodule update --init --recursive && shw_success "Updated prezto"

  #update oh my zsh
  cd "${ZDOTDIR:-$HOME}/.oh-my-zsh" && git pull && git submodule update --init --recursive && shw_success "Updated oh-my-zsh"

  cd $INSTALL_DIR
}

all() {
    update_terminals
    pip install --upgrade pip && shw_success "Updated PIP"
    update_z
}

main() {
    shw_start_init "Updating OSX or Ubuntu computer"
    all
    if [ "$(uname)" == "Darwin" ]; then
        shw_info "OSX System Detected"
        ./install_scripts/update-osx.sh
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        shw_info "Linux System Detected"
        ./install_scripts/update-ubuntu.sh
    fi

    source "${HOME}/.zshrc" && shw_success ".zshrc reloaded"
    shw_success_final "Updating OSX or Ubuntu computer"
}
main
